CREATE TABLE `h_ujian` (
  `ID_H_UJIAN` int(11) NOT NULL,
  `ID_D_KELAS` int(11) NOT NULL,
  `ID_MAPEL` int(11) NOT NULL,
  `ID_TPUJIAN` int(11) NOT NULL,
  `NILAI_H_UJIAN` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `h_ujian`
  ADD PRIMARY KEY (`ID_H_UJIAN`),
  ADD KEY `FK_H_UJIAN_RELATIONS_D_KELAS` (`ID_D_KELAS`),
  ADD KEY `FK_H_UJIAN_RELATIONS_MAPEL` (`ID_MAPEL`),
  ADD KEY `FK_H_UJIAN_RELATIONS_TPUJIAN` (`ID_TPUJIAN`);

ALTER TABLE `h_ujian`
  ADD CONSTRAINT `FK_H_UJIAN_RELATIONS_D_KELAS` FOREIGN KEY (`ID_D_KELAS`) REFERENCES `d_kelas` (`ID_D_KELAS`),
  ADD CONSTRAINT `FK_H_UJIAN_RELATIONS_MAPEL` FOREIGN KEY (`ID_MAPEL`) REFERENCES `mapel` (`ID_MAPEL`),
  ADD CONSTRAINT `FK_H_UJIAN_RELATIONS_TPUJIAN` FOREIGN KEY (`ID_TPUJIAN`) REFERENCES `tpujian` (`ID_TPUJIAN`);